### ISSUE TITLE
Can I automock a requests.Session attribute?

### ISSUE THREAD

**Issue by ubalklen** [pohmelie/pytest-automock#4]
Can I automock a `requests.Session` object that is an attribute of a class? For example:

```
import requests

class MyClass():
   def __init__(self):
      self.session = requests.Session()

   def get_and_do_stuff(self, url):
      r = self.session.get(url)
      # Do stuff
```

I want to automock `MyClass.session` but not the whole `MyClass`. Is that possible?

**Comment by pksol** [comment]
I believe that the session object might not be serializable. 

So a different approach would be to refactor your code to: 


```
import requests

class MyClass():
   def __init__(self):
      self.session = requests.Session()

   def _get_data_from_session(self, url):
      r = self.session.get(url)
      # do any other parsing/conversions you may need
      return data

   def get_and_do_stuff(self, url):
      data = self._get_data_from_session(url)
      # Do stuff with the data

```

Then you can record and replace the `_get_data_from_session` method only.

**Comment by pohmelie** [comment]
@ubalklen 
> Can I automock a requests.Session object that is an attribute of a class?

Of course you can. If, and only if, `requests.Session` is serializable. You can achieve this with something like:

``` python
@pytest.fixture(autouse=True)
def _mocks(automock):
    with automock("requests.Session"):
        yield
```

Also, I agreed with @pksol, if this wont work and `Session` class is not serializable, then just move your methods out of class and mock them:

``` python
import requests

def _get_data_from_session(session, url):
    r = session.get(url)
    # do any other parsing/conversions you may need
    return data

class MyClass():
   def __init__(self):
      self.session = requests.Session()

   def get_and_do_stuff(self, url):
      data = _get_data_from_session(self.session, url)
      # Do stuff with the data
```

**Comment by ubalklen** [comment]
Thank you all for the answers.

But it's not clear to me why moving the session out of the class would work. Could please provide some explanation?

**Comment by pohmelie** [comment]
`pytest-automock` serialize only input and output of calls. If you try to "automock" `requests.Session` class, then all of the `Session` methods calls will be (tried to, actually) serialized (input and output). But there are lots of objects in python, that can't be serialized with pickle (socket, for example). Also, you will have useless amount of serialized calls for `Session` object. Instead of one call for your real data manipulation.

**Comment by ubalklen** [comment]
Right. Then, in that case, would I have to mock `_get_data_from_session`?

**Comment by pohmelie** [comment]
Yes, exactly.

**Comment by pohmelie** [comment]
BTW, reopen if this won't work, maybe `session` is not serializable too.
